AllCops:
  DisplayCopNames: true
  Exclude:
    - 'lib/capistrano/**/*'
    - 'vendor/bootstrap_form/**/*'
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 16
Metrics/MethodLength:
  Max: 20

Documentation:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Not:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/TrailingComma:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/TrailingBlankLines:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/DotPosition:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
